config/routes.rb
References::Application.routes.draw do
  get "citations/show"

  get "sessions/new"

  resources :users
  resources :citations
  resources :sessions, :only => [:new, :create, :destroy]
  resources :comments, :only => [:create, :destroy]
  resources :projects
  resources :categories
  resources :authors, :only => [:show]
  
  match '/sign_up', :to => 'users#new'
  match '/sign_in', :to => 'sessions#new'
  match '/sign_out', :to => 'sessions#destroy'
  root :to => 'pages#home'

end

app/models/citation.rb
class Citation < ActiveRecord::Base

has_many :citation_author_relationships, :foreign_key => "citation_id"
has_many :authors, :through => :citation_author_relationships
has_many :comments
has_and_belongs_to_many :projects
has_and_belongs_to_many :categories
   
  def self.search(search, method, page)
    if search
      if method == "title_or_abstract"
        paginate :per_page => 50, :page => page, :conditions => ['citations.title LIKE :search
                              OR citations.abstract LIKE :search', {:search => "%#{search}%"} ]
      elsif method == "author"
        paginate :per_page => 50, :page => page, :joins => :authors,
                   :conditions => ['authors.name LIKE :search', {:search => "%#{search}%"} ]
      end
    else
      paginate :per_page => 50, :page => page
    end
  end
 
  def ordered_authors()
    authors = Array.new
    relations = CitationAuthorRelationship.where(["citation_id = ?", id]).order("author_order ASC")
    relations.each do |relation|
       author = Author.find(relation.author_id)
       authors << author
    end
    return authors
  end
 
end
# == Schema Information
#
# Table name: citations
#
#  id              :integer(4)      not null, primary key
#  title           :text
#  abstract        :text
#  pubmed_url      :text
#  file_location   :text
#  citation_type  :string(255)
#  journal         :string(255)
#  issue           :string(255)
#  volume          :string(255)
#  pages           :string(255)
#  conference      :text
#  patent_assignee :string(255)
#  patent_number   :string(255)
#  publisher       :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  publish_year    :string(255)
#  author_list     :text
#

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  
  def index
    @citations = Citation.search(params[:search], params[:search_method], params[:page])
  end

  def show
    @citation = Citation.find(params[:id])
  end
  
  def edit
    @citation = Citation.find(params[:id])
  end
  
  def update
    @citation = Citation.find(params[:id])
    if params[:project].nil? == false
      if @project = Project.find_by_id(params[:project][:id])
        @citation.projects << @project
        flash[:success] = "project added successfully"
        redirect_to @citation
      else
        flash[:error] = "Failure to update projects: you must select a valid project to add."
        render 'edit'
      end
    elsif params[:category].nil? == false
      if @category = Category.find_by_id(params[:category][:id])
        @citation.categories << @category
        flash[:success] = "category added successfully"
        redirect_to @citation
      else
        flash[:error] = "Failure to update categories: you must select a valid category to add."
        render 'edit'
      end
      
    else
      render 'edit'
    end
    
  end
  
end

app/helpers/citations_helper.rb
module CitationsHelper
  
end

app/views/citations/_authorless_reference_string.html.erb
<% if citation.citation_type == "journal"%>
	<% if !citation.journal.blank? && !citation.publish_year.blank? && !citation.volume.blank? && !citation.pages.blank? %>
		<i><%= citation.journal %></i> <b><%= citation.publish_year %></b>,
		<%= citation.volume%>, <%= citation.pages %>.
	<% elsif !citation.journal.blank? %>
		<i><%= citation.journal %></i>
		<% unless citation.publish_year.blank? %>
			<b><%= citation.publish_year %></b>
		<% end %>
		<% unless citation.volume.blank?%>
			<%= ", " + citation.volume %>
		<% end %>
		<% unless citation.pages.blank? %>
			<%= ", " + citation.pages %>
		<% end %>
	<% else %>
	<% end %>

<% elsif citation.citation_type == "patent" %>
	<%= citation.patent_number %>
<% elsif citation.citation_type == "book" %>
	<%= citation.title %>; <%= citation.publisher %>: <%= citation.publish_year %>.	
<% end %>

app/views/citations/_authors.html.erb
<% authors = @citation.ordered_authors() %>
<% authors.each_with_index do |author, index| %>
	<%= link_to author.name, author %>
	<% unless index == (authors.size - 1) %>
		<%= "; "%>
	<% end %>
<% end %>

app/views/citations/_reference_string.html.erb
<% if @citation.citation_type == "journal"%>
	<% if !@citation.journal.blank? && !@citation.publish_year.blank? && !@citation.volume.blank? && !@citation.pages.blank? %>
		<%= @citation.author_list%> <i><%= @citation.journal %></i> <b><%= @citation.publish_year %></b>,
		<%= @citation.volume%>, <%= @citation.pages %>.
	<% elsif !@citation.journal.blank? %>
		<%= @citation.author_list%> <i><%= @citation.journal %></i>
		<% unless @citation.publish_year.blank? %>
			<b><%= @citation.publish_year %></b>
		<% end %>
		<% unless @citation.volume.blank?%>
			<%= ", " + @citation.volume %>
		<% end %>
		<% unless @citation.pages.blank? %>
			<%= ", " + @citation.pages %>
		<% end %>
	<% else %>
	<% end %>

<% elsif @citation.citation_type == "patent" %>
	<%= @citation.patent_number %>
<% elsif @citation.citation_type == "book" %>
	<%= @citation.author_list %> <%= @citation.title %>; <%= @citation.publisher %>: <%= @citation.publish_year %>.	
<% end %>

app/views/citations/edit.html.erb
<section>
<h3>Edit relations for reference# <%= @citation.id%>:</h3>
<%= form_for @citation do |f|%>
	<%= f.label :project %><br>
	<%= collection_select :project, :id, Project.all-@citation.projects, :id, :name, :include_blank => "Select a project" %>
	<%= f.submit "add" %>
<% end %>
<p></p>
<%= form_for @citation do |f|%>
	<%= f.label :category %><br>
	<%= collection_select :category, :id, Category.all-@citation.categories, :id, :name, :include_blank => "Select a category" %>
	<%= f.submit "add" %>
<% end %>



</section>

app/views/citations/index.html.erb
<section id="table_section">
<h3>Results for search "<%= params[:search]%>":</h3>
<%= will_paginate %>
<table>
	<thead>
		<tr class="table_header">
			<th id="ref_table_title_head" width="20%">Title</th>
			<th id="ref_table_abstract_head" width="40">Comments</th>
			<th id="ref_table_author_head" width="30%">Authors</th>
			<th id="ref_table_journal_head" width="10%">Citation</th>
		</tr>
	</thead>
	<tbody>
		<% @citations.each do |ref| %>
		  <tr>
		    <td>
		    	<% unless ref.title.nil? %> 
		    		<%= link_to ref.title, ref %>
		    	<% else %>
		    		<%= "no title"%>
		    	<% end %>
	    	</td>
	    	<td id="comments">
	    		<%ref.comments.each do |comment|%>
						<% unless ref.comments.nil? %>
							<b><%= comment.user.first_name + " " + comment.user.last_name + ": " %></b><%= comment.content %><br>
						<% end %>
					<% end %>
    		</td>
		    <td>
		    	<% unless ref.author_list.empty? %> 
		    	<%= ref.author_list %>
		    	<% end %>
	    	</td>
	    	<td>
	    		<% if ref.citation_type == "journal" %>
		    		<%= render :partial => "authorless_reference_string", :locals => { :citation => ref} %>
	    		<% elsif ref.citation_type == "patent" %>
	    			<% unless ref.patent_number.nil? %> 
		    			<%= ref.patent_number %>
		    		<% end %>
	    		<% end %>
	    	</td>
		  </tr>
		<% end %>
	</tbody>
</table>
<%= will_paginate %>
</section>

app/views/citations/show.html.erb
<section id="citation">
	<h3><%= @citation.title %></h3>
	<div id="citation_info">
		<b>Citation ID:</b> <%= @citation.id %><br>
		<b>Authors:</b> <%= render :partial => "authors" %><br>
		<b>Citation:</b> <%= render :partial => "reference_string" %><br>	
		<b>File Location:</b> <%= link_to(@citation.file_location, @citation.file_location) %><br>
		<b>Abstract:</b> <%= @citation.abstract %><br>
	</div>
	<br>
	<p><b>Tagged projects: </b><% if @citation.projects.empty?%><%= "none"%>
	<% else %>
		<% @citation.projects.each_with_index do |project, index|%>
			<% if index == @citation.projects.size() - 1 %>
				<%= link_to(project.name, project_path(project)) + "." %>
			<% else %>
				<%= link_to(project.name, project_path(project)) + ", " %>
			<% end %>
		<% end %>
	<% end %> </p>
	<p><b>Tagged categories: </b><% if @citation.categories.empty?%><%= "none"%>
	<% else %>
		<% @citation.categories.each_with_index do |category, index| %>
			<% if index == @citation.categories.size() - 1 %>
				<%= link_to(category.name, category_path(category)) + "." %>
			<% else %>
				<%= link_to(category.name, category_path(category)) + ", " %>
			<% end %>
		<% end %>
	<% end %> </p>	
			
	<p><%= link_to "Add", edit_citation_path(@citation) %> projects and categories of this citation</p>
	
</section>

<section id="add_comment">
	<h3>Add a comment:</h3>
	<% @comment = Comment.new%>
	<%= form_for @comment do |f|%>
		<%= f.text_area :content %>
		<%= f.hidden_field :citation_id, :value => @citation.id %>
		<%= f.submit "submit" %>
	<% end %>
</section>
<section id="comments">
	<h3>Comments:</h3>
	<%@citation.comments.each_with_index do |comment, index|%>
		<% unless @citation.comments.nil? %>
			<% if index.odd? %>
				<%=raw "<div class=\"comment_odd\">" %>
			<% else %>
				<%=raw "<div class=\"comment_even\">" %>
			<% end %>
			<p><b><%= comment.user.first_name + " " + comment.user.last_name %></b> wrote on
				<%= comment.created_at %>:</p>
			<p class="comment_content"><%= comment.content %></p>
			<%=raw "</div>"%>
		<% end %>
	<% end %>
</section>

app/views/citations/update.html.erb
<%= @stuff %>