config/routes.rb
References::Application.routes.draw do
  get "citations/show"

  get "sessions/new"

  resources :users
  resources :citations
  resources :sessions, :only => [:new, :create, :destroy]
  resources :comments, :only => [:create, :destroy]
  resources :projects
  resources :categories
  resources :authors, :only => [:show]
  
  match '/sign_up', :to => 'users#new'
  match '/sign_in', :to => 'sessions#new'
  match '/sign_out', :to => 'sessions#destroy'
  root :to => 'pages#home'

end

app/views/pages/home.html.erb
<script>
	$(function() {
		$( '#tabs' ).tabs();
	});
</script>
<section>
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Search</a></li>
		<li><a href="#tabs-2">Projects</a></li>
		<li><a href="#tabs-3">Categories</a></li>
		<li><a href="#tabs-4">Recent Comments</a></li>
	</ul>
	<div id="tabs-1">
		<h2>Search references:</h2>
		<p>
			<%= form_tag citations_path, :method => 'get' do %>
		    <%= label_tag 'Title/Abstract Search:' %> <%= text_field_tag :search, params[:search] %>
		    <%= hidden_field_tag :search_method, "title_or_abstract"%>
		    <%= submit_tag "Search", :name => nil %>
			<% end %>
		</p>
		<p>
			<%= form_tag citations_path, :method => 'get' do%>
		    <%= label_tag 'Author Search:' %> <%= text_field_tag :search, params[:search] %>
		    <%= hidden_field_tag :search_method, "author"%>
		    <%= submit_tag "Search", :name => nil %>
			<% end %>
		</p>
	</div>	
	<div id="tabs-2">
		<ul>
			<% @project.each do |p| %>
				<%=raw "<li>" + link_to(p.name.capitalize, project_path(p)) + "</li>" %>
			<% end %>
		</ul>
		<p><%= link_to "Add a new project", new_project_path %></p>
	</div>
	<div id="tabs-3">
		<ul>
			<% @category.each do |c| %>
				<li><a href="<%= category_path(c) %>"><%= c.name %></a></li>
			<% end %>
		</ul>
		<p><%= link_to "Add a new category", new_category_path %></p>
	</div>
	<div id="tabs-4">
		<ul>
			<% @comments.each do |comment| %>
				<li><a href="<%= citation_path(comment.citation_id) %>"><%= comment.citation.title%></a>
					<br><p class="indented"><%= comment.user.first_name %> <%= comment.user.last_name %>:
						 <%= comment.content %> (<%= comment.updated_at %>)</p>
				</li>
			<% end %>
		</ul>
	</div>
</div>
</section>

app/views/pages/sign_in.html.erb
<h1>Pages#sign-in</h1>
<p>Find me in app/views/pages/sign-in.html.erb</p>

app/views/pages/sign_up.html.erb
<h1>Pages#sign-up</h1>
<p>Find me in app/views/pages/sign-up.html.erb</p>