config/routes.rb
References::Application.routes.draw do
  get "citations/show"

  get "sessions/new"

  resources :users
  resources :citations
  resources :sessions, :only => [:new, :create, :destroy]
  resources :comments, :only => [:create, :destroy]
  resources :projects
  resources :categories
  resources :authors, :only => [:show]
  
  match '/sign_up', :to => 'users#new'
  match '/sign_in', :to => 'sessions#new'
  match '/sign_out', :to => 'sessions#destroy'
  root :to => 'pages#home'

end

app/views/layouts/_header.html.erb
<header>
	<div class="header">
		<h1 class="title"> Reference Navigator</h1>
		<nav class="round">
			<ul>
	  		<li><%= link_to "Home", root_path %></li>  
	  		<% if current_user %>
					<li><%= link_to "Sign Out", sign_out_path %></li>
					<li></li>
					<li><%=raw "Logged in as <b>#{current_user.first_name} #{current_user.last_name}</b>" %></li>
	  		<% else %>
					<li><%= link_to "Sign Up", sign_up_path %></li>
					<li><%= link_to "Sign In", sign_in_path %></li>
	  		<% end %>      
			</ul> 
	  </nav>
  </div>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9}>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<!-- [if lt IE 8><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'jquery-1.7.2.min.js', 'jquery-ui-1.8.22.custom.min.js' %>
  <%= stylesheet_link_tag 'jquery-ui-1.8.22.custom.css'%>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <selection class="round">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    </selection>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>